


version: "3.8"
services:
  backend:
    image: "cgteate/springboot-react-fullstack:17.3.2023.2.53.54"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      