


version: "3.8"
services:
  backend:
    image: "cgteate/springboot-react-fullstack:14.3.2023.15.43.53"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev