


version: "3.8"
services:
  backend:
    image: "cgteate/springboot-react-fullstack:latest"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}