


version: "3.8"
services:
  backend:
    image: "cgteate/springboot-react-fullstack:16.3.2023.22.21.49"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      